/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.cheetah.youbet.gui.component;

/**
 *
 * @author edoardo
 */
public class StatistichePanel extends javax.swing.JPanel {

    /**
     * Creates new form StatistichePanel
     */
    public StatistichePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        comboTipoInfo = new javax.swing.JComboBox();
        scrollPaneResult = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();
        labelNomeCompetizione = new javax.swing.JLabel();
        labelNomeSquadra = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        comboTipoInfo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ultimi 5 incontri" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        add(comboTipoInfo, gridBagConstraints);

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneResult.setViewportView(tableResult);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(scrollPaneResult, gridBagConstraints);

        labelNomeCompetizione.setText("Nome Competizione");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.3;
        add(labelNomeCompetizione, gridBagConstraints);

        labelNomeSquadra.setText("Nome squadra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.2;
        add(labelNomeSquadra, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboTipoInfo;
    private javax.swing.JLabel labelNomeCompetizione;
    private javax.swing.JLabel labelNomeSquadra;
    private javax.swing.JScrollPane scrollPaneResult;
    private javax.swing.JTable tableResult;
    // End of variables declaration//GEN-END:variables
}
