/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cheetah.youbet.gui;

import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JSlider;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import org.cheetah.youbet.ContextSpringFactory;
import org.cheetah.youbet.entities.Palinsesto;
import org.cheetah.youbet.gui.model.PalinsestoTableModel;
import org.cheetah.youbet.gui.model.PoissonTableModel;
import org.springframework.beans.BeansException;

/**
 *
 * @author edoardo
 */
public class PoissonDialog extends javax.swing.JFrame {

    private List<Palinsesto> palinsestos;

    /**
     * Creates new form PoissonFrame
     */
    public PoissonDialog(List<Palinsesto> palinsestos) {
        this.palinsestos = palinsestos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        palinsestoScrollPane = new javax.swing.JScrollPane();
        palinsestoTable = new javax.swing.JTable();
        poissonScrollPane = new javax.swing.JScrollPane();
        poissonTable = new javax.swing.JTable();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filtraPercentualeSlider = new javax.swing.JSlider();
        filtraPercentualeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setLayout(new java.awt.GridBagLayout());

        splitPane.setResizeWeight(0.5);

        palinsestoTable.setModel(new PalinsestoTableModel(this.palinsestos,
            new PalinsestoTableModel.PalinsestoColumn[]{PalinsestoTableModel.PalinsestoColumn.ID_PALINSESTO,
                PalinsestoTableModel.PalinsestoColumn.ID_AVVENIMENTO,PalinsestoTableModel.PalinsestoColumn.DESCRIZIONE}));
    palinsestoTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            palinsestoTableMouseClicked(evt);
        }
    });
    palinsestoTable.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            palinsestoTableKeyReleased(evt);
        }
    });
    palinsestoScrollPane.setViewportView(palinsestoTable);

    splitPane.setLeftComponent(palinsestoScrollPane);

    poissonTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
        },
        new String [] {
        }
    ));
    poissonScrollPane.setViewportView(poissonTable);

    splitPane.setRightComponent(poissonScrollPane);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    mainPanel.add(splitPane, gridBagConstraints);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Percentuale");
    topPanel.add(jLabel1);

    filtraPercentualeSlider.setMajorTickSpacing(5);
    filtraPercentualeSlider.setMaximum(15);
    filtraPercentualeSlider.setPaintLabels(true);
    filtraPercentualeSlider.setPaintTicks(true);
    filtraPercentualeSlider.setValue(0);
    filtraPercentualeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            filtraPercentualeSliderStateChanged(evt);
        }
    });
    topPanel.add(filtraPercentualeSlider);
    //filtraPercentualeSlider.setLabelTable(filtraPercentualeSlider.createStandardLabels(1));
    filtraPercentualeSlider.setPaintTicks(true);
    filtraPercentualeSlider.setPaintLabels(true);

    filtraPercentualeLabel.setText(Integer.toString(filtraPercentualeSlider.getValue()));
    topPanel.add(filtraPercentualeLabel);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    mainPanel.add(topPanel, gridBagConstraints);

    getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palinsestoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palinsestoTableMouseClicked
        changePalinsestoTableData();
    }

    private void changePalinsestoTableData() throws BeansException {
        Palinsesto palinsestoSelected = getPalinsestoRowSelected(palinsestoTable);
        PoissonTableModel model = ContextSpringFactory.getInstance().getContext().getBean(PoissonTableModel.class);
        initPoissonModel(model, palinsestoSelected);
        model.loadDataPercentualeGreaterThan(palinsestoSelected, filtraPercentualeSlider.getValue());
        poissonTable.setModel(model);
        JTableHeader header = poissonTable.getTableHeader();
        if (header.getColumnModel().getColumnCount() > 0) {
            TableColumn tableColumnHome = header.getColumnModel().getColumn(0);
            TableColumn tableColumnAway = header.getColumnModel().getColumn(1);
            tableColumnHome.setHeaderValue(palinsestoSelected.getHomeTeam());
            tableColumnAway.setHeaderValue(palinsestoSelected.getAwayTeam());
            header.repaint();
        }
        model.fireTableDataChanged();
    }

    private void initPoissonModel(PoissonTableModel model, Palinsesto palinsestoSelected) {
        model.setPalinsestoSelected(palinsestoSelected);
        model.setVisibleColumns(new PoissonTableModel.PoissonColumn[]{
            PoissonTableModel.PoissonColumn.GOL_HOME,
            PoissonTableModel.PoissonColumn.GOL_AWAY,
            PoissonTableModel.PoissonColumn.PERCENTUALE
        });

    }//GEN-LAST:event_palinsestoTableMouseClicked

    private Palinsesto getPalinsestoRowSelected(JTable table) {
        Palinsesto palinsestoSelected = palinsestos.get(table.getSelectedRow());
        return palinsestoSelected;
    }

    private void filtraPercentualeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_filtraPercentualeSliderStateChanged
        JSlider slider = (JSlider) evt.getSource();
        filtraPercentualeLabel.setText(Integer.toString(slider.getValue()));
        if (palinsestoTable.getSelectedRow() != -1) {
//            Palinsesto p = getPalinsestoRowSelected(palinsestoTable);
//            PoissonTableModel model = ContextSpringFactory.getInstance().getContext().getBean(PoissonTableModel.class);
//            initPoissonModel(model, p);
//            model.loadDataPercentualeGreaterThan(p,slider.getValue());
//            poissonTable.setModel(model);
//            model.fireTableDataChanged();
            changePalinsestoTableData();
        }


    }//GEN-LAST:event_filtraPercentualeSliderStateChanged

    private void palinsestoTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_palinsestoTableKeyReleased
        changePalinsestoTableData();
    }//GEN-LAST:event_palinsestoTableKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filtraPercentualeLabel;
    private javax.swing.JSlider filtraPercentualeSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane palinsestoScrollPane;
    private javax.swing.JTable palinsestoTable;
    private javax.swing.JScrollPane poissonScrollPane;
    private javax.swing.JTable poissonTable;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

}
