/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.cheetah.youbet.gui;

import org.cheetah.youbet.ContextSpringFactory;
import org.cheetah.youbet.bean.Bolletta;
import org.cheetah.youbet.gui.model.QuotaTableModel;

/**
 *
 * @author edoardo
 */
public class BollettaDaGiocareDialog extends javax.swing.JDialog {

    /**
     * Creates new form BollettaDaGiocareDialog
     */
    public BollettaDaGiocareDialog() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        QuotaTableModel model = createModel();
        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private QuotaTableModel createModel() {
        Bolletta bolletta = ContextSpringFactory.getInstance().getContext().getBean(Bolletta.class);
        QuotaTableModel model = new QuotaTableModel(bolletta.getQuotasSelected(), new QuotaTableModel.QuotaColumn[]{
            QuotaTableModel.QuotaColumn.ID_PALINSESTO,
            QuotaTableModel.QuotaColumn.ID_AVVENIMENTO,
            QuotaTableModel.QuotaColumn.DESCRIZIONE_CLASSE,
            QuotaTableModel.QuotaColumn.DESCRIZIONE_ESITO,
            QuotaTableModel.QuotaColumn.QUOTA
        });
        model.fireTableDataChanged();
        return model;
    }
}
