/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.cheetah.youbet.gui;

import java.util.ArrayList;
import javax.swing.JTable;
import org.cheetah.youbet.bean.Bolletta;
import org.cheetah.youbet.entities.Quota;
import org.cheetah.youbet.gui.model.QuotaTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author edoardo
 */
@Component
public class BollettaDaGiocareDialog extends javax.swing.JDialog {
    
    @Autowired
    private Bolletta bolletta;

    public Bolletta getBolletta() {
        return bolletta;
    }

    public void setBolletta(Bolletta bolletta) {
        this.bolletta = bolletta;
    }

    /**
     * Creates new form BollettaDaGiocareDialog
     */
    public BollettaDaGiocareDialog() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBolletta = new javax.swing.JPanel();
        scrollPaneBolletta = new javax.swing.JScrollPane();
        tableGiocata = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelBolletta.setLayout(new java.awt.GridBagLayout());

        QuotaTableModel model = createModel();
        tableGiocata.setModel(model);
        scrollPaneBolletta.setViewportView(tableGiocata);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelBolletta.add(scrollPaneBolletta, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(panelBolletta, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelBolletta;
    private javax.swing.JScrollPane scrollPaneBolletta;
    private javax.swing.JTable tableGiocata;
    // End of variables declaration//GEN-END:variables

    public JTable getTableGiocata() {
        return tableGiocata;
    }

    public void setTableGiocata(JTable tableGiocata) {
        this.tableGiocata = tableGiocata;
    }

    public QuotaTableModel createModel() {
        System.out.println("Bolletta: "+bolletta);
        QuotaTableModel.QuotaColumn[] visibleColumns = new QuotaTableModel.QuotaColumn[]{
            QuotaTableModel.QuotaColumn.ID_PALINSESTO,
            QuotaTableModel.QuotaColumn.ID_AVVENIMENTO,
            QuotaTableModel.QuotaColumn.DESCRIZIONE_CLASSE,
            QuotaTableModel.QuotaColumn.DESCRIZIONE_ESITO,
            QuotaTableModel.QuotaColumn.QUOTA
        };
        QuotaTableModel model = new QuotaTableModel(new ArrayList<Quota>(), visibleColumns);
        if(bolletta!=null){
        model = new QuotaTableModel(bolletta.getQuotasSelected(),visibleColumns );
        model.fireTableDataChanged();
        }
        return model;
    }
}
